### ISSUE TITLE
Following the documentation results in an error

### ISSUE THREAD

**Issue by Evertt** [denoland/manual#588]
I'm learning how to set up and use deno and I'm currently reading this page:

https://deno.land/manual@v1.31.2/getting_started/first_steps

But when I run the command
```
deno run --allow-net http_server.ts
```

As instructed here:
https://github.com/denoland/manual/blob/v1.31.2/getting_started/first_steps.md?plain=1#L178

I run into this error:

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'port')
  port = (server.addrs[0] as Deno.NetAddr).port;
                                           ^
    at serve (https://deno.land/std@0.179.0/http/server.ts:606:44)
    at file:///Users/evert/Sites/deno-chat-nvc/http_server.ts:22:1
```

I'd like to know how to fix this and the documentation should probably also be updated to include this answer.

**Comment by kt3k** [comment]
I can't reproduce the above issue. What is your OS & Deno versions?

**Comment by Evertt** [comment]
```
macOS 13.2.1
deno 1.31.2 (release, aarch64-apple-darwin)
v8 11.0.226.19
typescript 4.9.4
```

**Comment by kt3k** [comment]
Is your script the same as the below?:

```ts
import { serve } from "https://deno.land/std@0.179.0/http/server.ts";

const handler = async (_request: Request): Promise<Response> => {
  const resp = await fetch("https://api.github.com/users/denoland", {
    // The init object here has an headers object containing a
    // header that indicates what type of response we accept.
    // We're not specifying the method field since by default
    // fetch makes a GET request.
    headers: {
      accept: "application/json",
    },
  });

  return new Response(resp.body, {
    status: resp.status,
    headers: {
      "content-type": "application/json",
    },
  });
};

serve(handler);
```
